/* Generated by MyraPad at 2024-09-25 周三 下午 3:51:15 */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace Game.UI
{
	partial class UIMainMenu: Panel
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "GameOne";
			label1.TextColor = ColorStorage.CreateColor(91, 198, 250, 255);
			label1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;

			_menuItemStart = new MenuItem();
			_menuItemStart.Text = "Start";
			_menuItemStart.Id = "_menuItemStart";

			_menuItemOptions = new MenuItem();
			_menuItemOptions.Text = "Options";
			_menuItemOptions.Id = "_menuItemOptions";

			_menuItemQuit = new MenuItem();
			_menuItemQuit.Text = "Quit";
			_menuItemQuit.Id = "_menuItemQuit";

			var verticalMenu1 = new VerticalMenu();
			verticalMenu1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			verticalMenu1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			verticalMenu1.LabelHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			verticalMenu1.Border = new SolidBrush("#00000000");
			verticalMenu1.Background = new SolidBrush("#00000000");
			verticalMenu1.Items.Add(_menuItemStart);
			verticalMenu1.Items.Add(_menuItemOptions);
			verticalMenu1.Items.Add(_menuItemQuit);

			
			Background = new SolidBrush("#000000FF");
			Widgets.Add(label1);
			Widgets.Add(verticalMenu1);
		}

		
		public MenuItem _menuItemStart;
		public MenuItem _menuItemOptions;
		public MenuItem _menuItemQuit;
	}
}
