/* Generated by MyraPad at 2024-09-24 周二 下午 7:54:07 */
namespace Game.UI
{
	public partial class UIMainMenu
	{
		public UIMainMenu()
		{
			BuildUI();

			_menuItemStart.Selected += (sender, args) => OnClickStart();
			_menuItemOptions.Selected += (sender, args) => OnClickOptions();
			_menuItemQuit.Selected += (sender, args) => OnClickQuit();
		}

		public void OnClickStart()
		{

		}

		public void OnClickOptions()
		{

		}

		public void OnClickQuit()
		{
			FNAGame.Instance.Exit();
		}
	}
}